import Footer from 'components/common/Footer'
import Navbar from 'components/common/Navbar'
import Head from 'next/head'
import styles from '../../../styles/Home.module.css'

export default function profile () {
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />

    <main className={styles.main}>
    <div className="w-full relative mt-4 shadow-2xl rounded  overflow-hidden"/>
        <div className="top h-64 w-full bg-orange-600 overflow-hidden relative" >
        <div className="flex flex-col justify-center items-center relative h-full bg-black bg-opacity-50 text-white">
          <h1 className="text-2xl font-semibold">Webinars</h1>
          <h4 className="text-sm font-semibold">Pronto tendremos mas novedades</h4>
        </div>
    </div>
    <section>
    <div className="bg-orange-600 text-white py-8">
    <div className="container mx-auto flex flex-col items-start md:flex-row my-12 md:my-24">
      <div className="flex flex-col w-full sticky md:top-36 lg:w-1/3 mt-2 md:mt-12 px-8">
        <p className="ml-2 text-yellow-300 uppercase tracking-loose">Webinars Gratuitos</p>
        <p className="text-3xl md:text-4xl leading-normal md:leading-relaxed mb-2">Eventos del fin de semana</p>
        <p className="text-sm md:text-base text-gray-50 mb-4">
          Esto es una page.
        </p>
        <a href="#"
        className="bg-transparent mr-auto hover:bg-yellow-300 text-yellow-300 hover:text-white rounded shadow hover:shadow-lg py-2 px-4 border border-yellow-300 hover:border-transparent">
        Explorar todos</a>
      </div>
      <div className="ml-0 md:ml-12 lg:w-2/3 sticky">
        <div className="container mx-auto w-full h-full">
          <div className="relative wrap overflow-hidden p-10 h-full">
            <div className="border-2-2 border-yellow-555 absolute h-full border "
              style-="right: 50%; border: 2px solid #FFC100; border-radius: 1%;"></div>
            <div className="border-2-2 border-yellow-555 absolute h-full border"
              style-="left: 50%; border: 2px solid #FFC100; border-radius: 1%;"></div>
            <div className="mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline">
              <div className="order-1 w-5/12"></div>
              <div className="order-1 w-5/12 px-1 py-4 text-right">
                <p className="mb-3 text-base text-yellow-300">20, Febrero 2021</p>
                <h4 className="mb-3 font-bold text-lg md:text-2xl">CyberSecurity Basic</h4>
                <p className="text-sm md:text-base leading-snug text-gray-50 text-opacity-100">
                CyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity Basic
                </p>
              </div>
            </div>
            <div className="mb-8 flex justify-between items-center w-full right-timeline">
              <div className="order-1 w-5/12"></div>
              <div className="order-1  w-5/12 px-1 py-4 text-left">
                <p className="mb-3 text-base text-yellow-300">20, Febrero 20211</p>
                <h4 className="mb-3 font-bold text-lg md:text-2xl">CyberSecurity Basic</h4>
                <p className="text-sm md:text-base leading-snug text-gray-50 text-opacity-100">
                CyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity Basic
t.
                </p>
              </div>
            </div>
            <div className="mb-8 flex justify-between flex-row-reverse items-center w-full left-timeline">
              <div className="order-1 w-5/12"></div>
              <div className="order-1 w-5/12 px-1 py-4 text-right">
                <p className="mb-3 text-base text-yellow-300"> 20, Febrero 2021</p>
                <h4 className="mb-3 font-bold text-lg md:text-2xl">CyberSecurity Basic</h4>
                <p className="text-sm md:text-base leading-snug text-gray-50 text-opacity-100">
                CyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity Basic

                </p>
              </div>
            </div>

            <div className="mb-8 flex justify-between items-center w-full right-timeline">
              <div className="order-1 w-5/12"></div>

              <div className="order-1  w-5/12 px-1 py-4">
                <p className="mb-3 text-base text-yellow-300">20, Febrero 2021</p>
                <h4 className="mb-3 font-bold  text-lg md:text-2xl text-left">CyberSecurity Basic</h4>
                <p className="text-sm md:text-base leading-snug text-gray-50 text-opacity-100">
                CyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity BasicCyberSecurity Basic

                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </section>
    </main>

    <Footer />
  </div>
  )
}
